### PR TITLE
iPad 3D touch crash

### PR DESCRIPTION
**Pull request by mohsinalimat**
- 3D touch on app icon -> open add task then app is crash solve.

### CODE REVIEW

**Comment by rursache** [comment]
thanks

**Comment by mohsinalimat** [comment]
Most welcome.

[Mohsinali Matiya - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=fff0t)	[fff0t]

On March 19, 2020 at 13:43 GMT, Radu Ursache <notifications@github.com> wrote:

thanks

**Comment by mohsinalimat** [comment]
Can you please give me your email id?

[Mohsinali Matiya - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=fff30)	[fff30]

On March 19, 2020 at 14:52 GMT, Mohsinali Matiya <mmatiyailol@gmail.com> wrote:

Most welcome.

[Mohsinali Matiya - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=fff0t)	[fff0t]

On March 19, 2020 at 13:43 GMT, Radu Ursache <notifications@github.com> wrote:

thanks

**Comment by rursache** [comment]
radu [at] ursache [dott] com

**Pull request merged**
